name: "Build and deploy to GitHub"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/cache@v3
        id: cache-poetry
        with:
          path: ~/.local
          key: poetry-0
      - uses: snok/install-poetry@v1
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        with:
          version: "1.1.13"
          virtualenvs-create: true
          virtualenvs-in-project: true
      - id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: poetry install --no-interaction
      - run: PYTHONPATH=. poetry run sphinx-build -b html docs/doc docs/build
      - name: Deploy documentation
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/build/
