name: "Build docker container for release"

on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLISH_TOKEN }}
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
      - name: Change version
        run: |
          sed -i 's/^version = ".*"$/version = "${{ steps.meta.outputs.version }}"/g' pyproject.toml
          sed -i 's/^__version__ = ".*"$/__version__ = "${{ steps.meta.outputs.version }}"/g' server/__init__.py
      - uses: actions/setup-python@v4
        name: Setup python for changelog
        with:
          python-version: 3.9
      - run: pip install git+https://github.com/kapsner/auto-changelog.git
      - run: auto-changelog -t "Shardz - Master server"
      - name: Commit everything
        id: cpr
        uses: peter-evans/create-pull-request@v4.1.1
        with:
          commit-message: "docs(version): update version to ${{ steps.meta.outputs.version }}"
          add-paths: "pyproject.toml server/__init__.py CHANGELOG.md"
          branch: RELEASE-${{ steps.meta.outputs.version }}
          title: "docs(version): update version to ${{ steps.meta.outputs.version }}"
          token: ${{ secrets.PUBLISH_TOKEN }}
          labels: Release
          base: main
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
