name: "Build docker container for release"

on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLISH_TOKEN }}
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
      - name: Change version
        run: |
          sed -i 's/^version = ".*"$/version = "${{ steps.meta.outputs.version }}"/g' pyproject.toml
          sed -i 's/^__version__ = ".*"$/__version__ = "${{ steps.meta.outputs.version }}"/g' server/__init__.py
      - name: Commit version
        uses: EndBug/add-and-commit@v9
        with:
          message: "docs(version): update version to ${{ steps.meta.outputs.version }}"
          add: "pyproject.toml server/__init__.py"
          push: true
          new_branch: Release.actions
      - name: Generate changelog
        uses: BobAnkh/auto-generate-changelog@v1.2.2
        with:
          ACCESS_TOKEN: ${{secrets.PUBLISH_TOKEN}}
          BRANCH: main
          PULL_REQUEST: Release.actions
          TYPE: feat:Feature,fix:Fix,docs:Documentation,perf:Performance,build:Build,other:Other
          SUPPRESS_UNSCOPED: true
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
